/**
 * Minimal site chrome for MyNella (beauty / makeup marketing site).
 */

export const siteChromeSeed = {
  _id: "siteChrome" as const,
  _type: "siteChrome" as const,
  navigation: [
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
  ],
  ctaInvestorLogin: "https://www.mynella.com",
  ctaBookCall: "https://cal.com/mynella/talk",
  ctaBookOptimus: "https://www.mynella.com/contact",
  ctaBookPledgePlus: "https://www.mynella.com/contact",
  ctaBookPolaris: "https://www.mynella.com/contact",
  ctaBookPartnership: "https://www.mynella.com/contact",
  footerCompliance: [
    { label: "Terms", href: "/terms" },
    { label: "Privacy", href: "/privacy" },
  ],
  footerCompany: [
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
    { label: "Terms", href: "/terms" },
    { label: "Privacy", href: "/privacy" },
  ],
  socialLinks: [
    { id: "x", label: "X", href: "https://x.com/mynella" },
    { id: "linkedin", label: "LinkedIn", href: "https://www.linkedin.com/company/mynella" },
    { id: "substack", label: "Newsletter", href: "https://www.mynella.com" },
  ],
  brandName: "MyNella",
  brandTagline: "Makeup & beauty",
  logoAriaLabel: "MyNella — Home",
  heroPrimaryCtaLabel: "Book a call",
  heroStat1Value: "100",
  heroStat1Unit: "+",
  heroStat1Label: "Curated looks",
  heroStat2Value: "Clean",
  heroStat2Label: "Editorial standards",
  heroStat3Value: "24",
  heroStat3Unit: "h",
  heroStat3Label: "Typical reply time",
  heroStat4Value: "SEO",
  heroStat4Label: "Sanity + Next.js",
  strategyMatcherTrigger: "Find your routine",
  strategyMatcherPanelLead: "Pick a focus — we will point you to the right page. Everything here is illustrative until you edit copy in Sanity.",
  strategyMatcherBrowseAllLabel: "Browse about MyNella →",
  strategyMatcherBandsAria: "Beauty focus",
  strategyMatcherBands: [
    { id: "emerging", label: "Everyday", hint: "Quick routines & staples" },
    { id: "affluent", label: "Glam", hint: "Events & night-out looks" },
    { id: "hnw", label: "Pro", hint: "Artists & creators" },
  ],
  strategyMatcherPicksEmerging: [
    { title: "About", href: "/about", blurb: "Story, values, and how we work with brands." },
    { title: "Contact", href: "/contact", blurb: "Press, partnerships, and customer care." },
    { title: "Privacy", href: "/privacy", blurb: "How we handle data on this site." },
  ],
  strategyMatcherPicksAffluent: [
    { title: "Contact", href: "/contact", blurb: "Book time with the team." },
    { title: "Terms", href: "/terms", blurb: "Site terms and acceptable use." },
    { title: "About", href: "/about", blurb: "Learn what MyNella stands for." },
  ],
  strategyMatcherPicksHnw: [
    { title: "Book a call", href: "https://cal.com/mynella/talk", blurb: "Walk through campaigns or collaborations." },
    { title: "Email", href: "/contact", blurb: "Prefer async? Use the contact form." },
    { title: "Press kit", href: "/about", blurb: "Bio and assets (add in Studio)." },
  ],
  navMobileInvestorLogin: "Account",
  navMobileBookCall: "Book a call",
  navOverviewSuffix: "Overview",
  navToggleAria: "Toggle navigation",
  footerProductsTitle: "Explore",
  footerComplianceTitle: "Legal",
  footerCompanyTitle: "Company",
  footerSebiLine1: "MyNella is a content and commerce brand.",
  footerSebiLine2: "Replace these lines in Sanity with your registered business details.",
  footerSebiLine3: "© MyNella. All rights reserved.",
  footerCopyrightPrefix: "©",
  footerCopyrightOrg: "MyNella",
  skipToContentLabel: "Skip to content",
  companyLinkedInUrl: "https://www.linkedin.com/company/mynella",
  companyTagline: "Makeup tutorials, honest reviews, and editorial beauty content.",
  companyAbout:
    "MyNella is the public marketing site for a modern makeup brand. Swap this copy in Sanity Studio under Site chrome.",
  companyIndustry: "Beauty & personal care",
  companySizeBand: "Small team",
  companyHeadquarters: "Remote-first",
  companyLocations: [
    {
      label: "HQ",
      lines: ["Update in Sanity with your studio or office address."],
    },
  ],
  companySpecialties: ["Makeup", "Skincare", "Editorial", "Tutorials", "Product reviews"],
  headerUtilityLinks: [],
  footerProductNavLabels: [] as string[],
} as const;
